language: cpp

matrix:
  include:

    ## broken, PGI compiler cannot compile OpenMPI headers
    #- os: osx
    #  compiler: clang
    #  name: macOS - PGI 19.10
    #  env:
    #    - MATRIX_EVAL="brew update && brew install open-mpi fftw && brew upgrade cmake && curl --location --referer 'http://www.pgroup.com/products/community.htm' 'https://www.pgroup.com/support/downloader.php?file=pgi-community-macos-x64' -o PGI.dmg && hdiutil attach PGI.dmg && sudo installer -store -pkg '/Volumes/PGI 19.10/PGI 19.10.pkg' -target / && FC=/opt/pgi/osx86-64/19.10/bin/pgfortran"
    ## broken, cmake cannot find PGI integrated mpich
    #- os: osx
    #  compiler: clang
    #  name: macOS - PGI 19.10 - PGI mpich
    #  env:
    #    - MATRIX_EVAL="brew update && brew install fftw && brew upgrade cmake && curl --location --referer 'http://www.pgroup.com/products/community.htm' 'https://www.pgroup.com/support/downloader.php?file=pgi-community-macos-x64' -o PGI.dmg && hdiutil attach PGI.dmg && sudo installer -store -pkg '/Volumes/PGI 19.10/PGI 19.10.pkg' -target / && FC=/opt/pgi/osx86-64/19.10/bin/pgfortran && export ADDITIONAL_CMAKE_SETTINGS=\"-DMPI_C_HEADER_DIR=/opt/pgi/osx86-64/2019/mpi/mpich/include\""
    #- os: linux
    #  compiler: gcc
    #  name: ubuntu - PGI 19.10 - mpich
    #  addons:
    #    apt:
    #      update: true
    #      packages:
    #        - gfortran
    #        - libmpich-dev
    #        - libboost-all-dev
    #        - libfftw3-dev
    #        - libnuma-dev
    #        - libfftw3-mpi-dev
    #  env:
    #    - MATRIX_EVAL="curl --location --referer 'http://www.pgroup.com/products/community.htm' 'https://www.pgroup.com/support/downloader.php?file=pgi-community-linux-x64' -o pgilinux-x86-64.tar.gz && tar zxvf pgilinux-x86-64.tar.gz && export TEMPORARY_FILES=/tmp && export PGI_SILENT=true && export PGI_ACCEPT_EULA=accept && export PGI_INSTALL_DIR=/opt/pgi && export PGI_INSTALL_NVIDIA=false && export PGI_INSTALL_AMD=false && export PGI_INSTALL_JAVA=false && export PGI_INSTALL_MPI=false && export PGI_MPI_GPU_SUPPORT=false && export PGI_INSTALL_MANAGED=false && export VERBOSE=false && cd install_components && ./install && export PGI_VERSION=19.10 && export PGI=/opt/pgi && export PATH=/opt/pgi/linux86-64/19.10/bin:$PATH && export PATH=/opt/pgi/linux86-64/19.10/mpi/openmpi/bin:$PATH && export ADDITIONAL_CMAKE_SETTINGS=\"-DMPI_C_HEADER_DIR=/opt/pgi/linux86-64/19.10/mpi/openmpi/include\" && export MANPATH=$MANPATH:/opt/pgi/linux86-64/19.10/man && export LM_LICENSE_FILE=$LM_LICENSE_FILE:/opt/pgi/license.dat && FC=/opt/pgi/linux86-64/19.10/bin/pgfortran && cd .."

  #do not consider known failing builds for the whole build status
  allow_failures:
    - name: macOS - PGI 19.10
    - name: macOS - PGI 19.10 - PGI mpich
    - name: ubuntu - PGI 19.10 - mpich


before_install:
  - eval "${MATRIX_EVAL}"

before_script:
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE="Debug" -DCMAKE_Fortran_COMPILER=$FC ${ADDITIONAL_CMAKE_SETTINGS} -DFORCE_OLD_MPI:BOOL=ON

script:
  - cmake --build . --target install
