allreduce_dpreal – ALaDyn
allreduce_dpreal Subroutine
17 statements
Source File
public subroutine allreduce_dpreal(ib, rv_loc, rv, nt)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: ib
real(kind=dp), intent(in) :: rv_loc(:)
real(kind=dp), intent(out) :: rv(:)
integer, intent(in) :: nt
Calls
Called by
Contents
None
Call graph
allreduce_dpreal calls mpi_allreduce
envelope_struct_data calls allreduce_dpreal
enb_ionz calls allreduce_dpreal, bunch_corr
max_pmemory_check calls allreduce_dpreal
envar calls allreduce_dpreal, envelope_struct_data, enb_bunch
enb_hgam calls allreduce_dpreal, bunch_corr
fields_on_target calls allreduce_dpreal
laser_struct_data calls allreduce_dpreal
enb_bunch calls allreduce_dpreal, bunch_corr
bunch_corr calls allreduce_dpreal
timing calls max_pmemory_check
data_out calls envar
aladyn calls max_pmemory_check, lp_cycle, env_cycle
lp_cycle calls timing, data_out
env_cycle calls timing, data_out