beam_inject – ALaDyn
beam_inject Subroutine
114 statements
Source File
public subroutine beam_inject()
Arguments
None
Calls
Called by
Contents
None
Call graph
beam_inject calls ebfb, ebfp, pot, bunch, ebf_bunch, loc_npart, mpi_beam_ftgrid_distribute, init_random_seed, initial_beam_fields, loc_nbpart, p_alloc, spec, fill_ebfield_yzxbdsdata, lp_end, ebf, jc, beam_data, mpi_beam_distribute
mpi_beam_ftgrid_distribute calls ebfb, bunch, loc_nbpart
initial_beam_fields calls loc_yg, loc_zg
fill_ebfield_yzxbdsdata calls exchange_bdx_data
beam_data calls ebfb, exchange_2d_grdata, unit_charge
mpi_beam_distribute calls ebfb, bunch, loc_nbpart
env_cycle calls beam_inject
aladyn calls env_cycle