collect_bunch_and_plasma_density – ALaDyn
collect_bunch_and_plasma_density Subroutine
48 statements
Source File
public subroutine collect_bunch_and_plasma_density(this_bunch, isp)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: this_bunch
integer, intent(in) :: isp
Calls
Contents
None
Call graph
collect_bunch_and_plasma_density calls loc_yg, bunch, loc_npart, fill_curr_yzxbdsdata, loc_nbpart, spec, loc_zg, jc
fill_curr_yzxbdsdata calls exchange_bdx_data