comoving_coordinate – ALaDyn
comoving_coordinate Subroutine
33 statements
Source File
public subroutine comoving_coordinate(vb, w_nst, loc_it)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: vb
integer, intent(in) :: w_nst
integer, intent(in) :: loc_it
Calls
Called by
Contents
None
Call graph
comoving_coordinate calls cell_part_dist, particles_inject
cell_part_dist calls ebfp, v_realloc, loc_npart, spec
particles_inject calls add_particles, loc_npart, v_realloc
add_particles calls init_random_seed, gasdev
lp_run calls comoving_coordinate
env_run calls comoving_coordinate
lp_cycle calls lp_run
env_cycle calls env_run
aladyn calls lp_cycle, env_cycle