env_lpf2_evolve – ALaDyn
env_lpf2_evolve Subroutine
99 statements
Source File
public subroutine env_lpf2_evolve(it_loc)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: it_loc
Calls
Called by
Contents
None
Call graph
env_lpf2_evolve calls loc_npart, env_amp_two_fields_prepare, env_two_fields_average, update_adam_bash_fluid_variables, ion_min, init_random_seed, enable_ionization, curr_mpi_collect, set_env_density, ebfp, fluid_curr_accumulate, spec, env_amp_prepare, jc, advance_lpf_fields, env_den_collect, set_env_momentum_density_flux, env_fields_average, flux, advance_lpf_envelope, atomic_number
env_amp_two_fields_prepare calls env_grad
update_adam_bash_fluid_variables calls lorentz_fact, field_xyzbd, unit_charge, fill_ebfield_yzxbdsdata, nc_fluid_density_momenta
curr_mpi_collect calls fill_curr_yzxbdsdata, djc, jc_xyzbd
fluid_curr_accumulate calls field_xyzbd, unit_charge, fill_ebfield_yzxbdsdata
env_amp_prepare calls env_grad
advance_lpf_fields calls rote, ef_bds, rotb, field_xadvect, fill_ebfield_yzxbdsdata, bf_bds
env_den_collect calls fill_curr_yzxbdsdata, den_zyxbd, loc_yg, loc_zg
env_fields_average calls env_grad
advance_lpf_envelope calls env_lpf_solve, env_maxw_solve, env_bds, fill_ebfield_yzxbdsdata
env_lpf_solve calls pp_lapl
fill_curr_yzxbdsdata calls exchange_bdx_data
rote calls loc_yg, loc_zg
env_maxw_solve calls potential_lapl
env_bds calls loc_yg, loc_zg
ef_bds calls loc_yg, loc_zg, loc_zgrid, loc_xg
rotb calls loc_yg, loc_zg
field_xadvect calls trid_der1
fill_ebfield_yzxbdsdata calls exchange_bdx_data
nc_fluid_density_momenta calls loc_yg, loc_zg
bf_bds calls loc_yg, loc_zg, loc_xg
pp_lapl calls loc_yg, loc_zg
env_run calls env_lpf2_evolve
env_cycle calls env_run
aladyn calls env_cycle