env_run – ALaDyn
env_run Subroutine
23 statements
Source File
public subroutine env_run(t_loc, iter_loc)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: t_loc
integer, intent(in) :: iter_loc
Calls
Called by
Contents
None
Call graph
env_run calls lp_window_xshift, comoving_coordinate, env_lpf2_evolve
lp_window_xshift calls fluid_left_xshift, fields_left_xshift, part_numbers, particles_inject, cell_part_dist
comoving_coordinate calls particles_inject, cell_part_dist
env_lpf2_evolve calls loc_npart, env_amp_two_fields_prepare, env_two_fields_average, update_adam_bash_fluid_variables, ion_min, init_random_seed, enable_ionization, curr_mpi_collect, set_env_density, ebfp, fluid_curr_accumulate, spec, env_amp_prepare, jc, advance_lpf_fields, env_fields_average, env_den_collect, set_env_momentum_density_flux, flux, advance_lpf_envelope, atomic_number
env_amp_two_fields_prepare calls env_grad
update_adam_bash_fluid_variables calls lorentz_fact, field_xyzbd, unit_charge, fill_ebfield_yzxbdsdata, nc_fluid_density_momenta
fluid_left_xshift calls exchange_bdx_data
fields_left_xshift calls exchange_bdx_data
part_numbers calls loc_npart, intvec_distribute
curr_mpi_collect calls fill_curr_yzxbdsdata, djc, jc_xyzbd
particles_inject calls loc_npart, add_particles, v_realloc
fluid_curr_accumulate calls field_xyzbd, unit_charge, fill_ebfield_yzxbdsdata
env_amp_prepare calls env_grad
advance_lpf_fields calls rote, ef_bds, rotb, field_xadvect, fill_ebfield_yzxbdsdata, bf_bds
env_fields_average calls env_grad
env_den_collect calls fill_curr_yzxbdsdata, den_zyxbd, loc_yg, loc_zg
cell_part_dist calls loc_npart, ebfp, spec, v_realloc
advance_lpf_envelope calls env_lpf_solve, env_maxw_solve, env_bds, fill_ebfield_yzxbdsdata
env_lpf_solve calls pp_lapl
fill_curr_yzxbdsdata calls exchange_bdx_data
rote calls loc_yg, loc_zg
env_maxw_solve calls potential_lapl
add_particles calls init_random_seed, gasdev
env_bds calls loc_yg, loc_zg
ef_bds calls loc_yg, loc_zg, loc_zgrid, loc_xg
rotb calls loc_yg, loc_zg
field_xadvect calls trid_der1
fill_ebfield_yzxbdsdata calls exchange_bdx_data
nc_fluid_density_momenta calls loc_yg, loc_zg
intvec_distribute calls mpi_send, mpi_bcast, mpi_recv
bf_bds calls loc_yg, loc_zg, loc_xg
pp_lapl calls loc_yg, loc_zg
env_cycle calls env_run
aladyn calls env_cycle