Env_cycle – ALaDyn
Env_cycle Subroutine
23 statements
Source File
subroutine Env_cycle()
Arguments
None
Calls
Called by
Contents
None
Call graph
env_cycle calls beam_inject, data_out, env_run, timing, part_numbers, error_message
beam_inject calls pot, loc_npart, mpi_beam_ftgrid_distribute, beam_data, bunch, ebf_bunch, lp_end, init_random_seed, p_alloc, ebf, mpi_beam_distribute, ebfb, ebfp, spec, fill_ebfield_yzxbdsdata, jc, initial_beam_fields, loc_nbpart
data_out calls fluid_den_mom_out, create_timestep_folder, prl_den_energy_interp, part_pdata_out, fields_out_new, envar, env_two_fields_out, fields_out, env_fields_out, den_energy_out
env_run calls comoving_coordinate, env_lpf2_evolve, lp_window_xshift
timing calls part_numbers, tot_num_part, max_pmemory_check
part_numbers calls loc_npart, intvec_distribute
mpi_beam_ftgrid_distribute calls bunch, ebfb, loc_nbpart
fluid_den_mom_out calls endian, exchange_pdata
beam_data calls ebfb, exchange_2d_grdata, unit_charge
comoving_coordinate calls particles_inject, cell_part_dist
prl_den_energy_interp calls loc_npart, spec, jc, env, den_zyxbd, mass, loc_yg, loc_zg
env_lpf2_evolve calls loc_npart, init_random_seed, ebfp, spec, jc, env_amp_two_fields_prepare, env_two_fields_average, update_adam_bash_fluid_variables, ion_min, enable_ionization, curr_mpi_collect, set_env_density, fluid_curr_accumulate, env_amp_prepare, advance_lpf_fields, env_fields_average, env_den_collect, set_env_momentum_density_flux, flux, advance_lpf_envelope, atomic_number
mpi_beam_distribute calls bunch, ebfb, loc_nbpart
part_pdata_out calls loc_npart, intvec_distribute, mpi_write_part, endian
fields_out_new calls mpi_write_field, endian
envar calls loc_npart, envelope_struct_data, mass, enb_bunch, allreduce_dpreal
fill_ebfield_yzxbdsdata calls exchange_bdx_data
env_two_fields_out calls exchange_pdata
lp_window_xshift calls part_numbers, fluid_left_xshift, fields_left_xshift, particles_inject, cell_part_dist
intvec_distribute calls mpi_send, mpi_recv, mpi_bcast
tot_num_part calls loc_npart
max_pmemory_check calls allreduce_dpreal
fields_out calls endian, exchange_pdata
initial_beam_fields calls loc_yg, loc_zg
env_fields_out calls exchange_pdata
den_energy_out calls endian, exchange_pdata
envelope_struct_data calls allreduce_dpreal
mpi_write_part calls mpi_file_close, mpi_file_set_view, mpi_file_write, mpi_file_open
env_amp_two_fields_prepare calls env_grad
update_adam_bash_fluid_variables calls fill_ebfield_yzxbdsdata, unit_charge, lorentz_fact, field_xyzbd, nc_fluid_density_momenta
fluid_left_xshift calls exchange_bdx_data
fields_left_xshift calls exchange_bdx_data
curr_mpi_collect calls fill_curr_yzxbdsdata, djc, jc_xyzbd
particles_inject calls loc_npart, add_particles, v_realloc
fluid_curr_accumulate calls fill_ebfield_yzxbdsdata, unit_charge, field_xyzbd
mpi_write_field calls mpi_file_close, mpi_file_set_view, mpi_file_write, mpi_file_open
env_amp_prepare calls env_grad
advance_lpf_fields calls fill_ebfield_yzxbdsdata, rote, ef_bds, rotb, field_xadvect, bf_bds
enb_bunch calls loc_npart, allreduce_dpreal, bunch_corr
env_fields_average calls env_grad
env_den_collect calls loc_yg, loc_zg, fill_curr_yzxbdsdata, den_zyxbd
cell_part_dist calls loc_npart, ebfp, spec, v_realloc
advance_lpf_envelope calls fill_ebfield_yzxbdsdata, env_lpf_solve, env_bds, env_maxw_solve
allreduce_dpreal calls mpi_allreduce
env_lpf_solve calls pp_lapl
fill_curr_yzxbdsdata calls exchange_bdx_data
bunch_corr calls allreduce_dpreal
rote calls loc_yg, loc_zg
add_particles calls init_random_seed, gasdev
env_bds calls loc_yg, loc_zg
ef_bds calls loc_yg, loc_zg, loc_zgrid, loc_xg
rotb calls loc_yg, loc_zg
field_xadvect calls trid_der1
nc_fluid_density_momenta calls loc_yg, loc_zg
env_maxw_solve calls potential_lapl
bf_bds calls loc_yg, loc_zg, loc_xg
pp_lapl calls loc_yg, loc_zg
aladyn calls env_cycle