fft_3d_psolv – ALaDyn
fft_3d_psolv Subroutine
53 statements
Source File
public subroutine fft_3d_psolv(rho, pot1, g2, omp0, n1, n1_loc, n2, n2_loc, n3, n3_loc, i1, i2, j1, j2, k1, k2, ft_mod, sym, s_ind)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(inout) :: rho(:,:,:,:)
real(kind=dp), intent(inout) :: pot1(:,:,:,:)
real(kind=dp), intent(in) :: g2
real(kind=dp), intent(in) :: omp0
integer, intent(in) :: n1
integer, intent(in) :: n1_loc
integer, intent(in) :: n2
integer, intent(in) :: n2_loc
integer, intent(in) :: n3
integer, intent(in) :: n3_loc
integer, intent(in) :: i1
integer, intent(in) :: i2
integer, intent(in) :: j1
integer, intent(in) :: j2
integer, intent(in) :: k1
integer, intent(in) :: k2
integer, intent(in) :: ft_mod
integer, intent(in) :: sym
integer, intent(in) :: s_ind
Calls
Contents
None
Call graph
fft_3d_psolv calls pftw3d_sc, ftw_init, pftw3d, ftw_end, ft_overset_grid, all_gather_dpreal, mpi_ftw_alloc, mpi_yzft_ord, mpi_ftw_dalloc, unif_to_str_field_interp, beam_potential
pftw3d_sc calls ftw1d_sc, pftw2d_sc
pftw3d calls pftw2d, ftw1d
ft_overset_grid calls comm_col, yp_prev, yp_next, zp_prev, zp_next
unif_to_str_field_interp calls zft_ind, loc_zft, loc_yft, loc_yg, yft_ind, loc_zg
ftw1d_sc calls fftw_execute_r2r, determine_kind, logical_dimension
pftw2d_sc calls ftw1d_sc, swap_xz_3data_inv, swap_xz_3data, swap_xy_3data, swap_xy_3data_inv
pftw2d calls ftw1d, swap_xz_3data_inv, swap_xz_3data, swap_xy_3data, swap_xy_3data_inv
ftw1d calls fftw_execute_dft_c2r, fftw_execute_dft_r2c
swap_xz_3data_inv calls comm_col, zp_prev, zp_next
swap_xz_3data calls comm_col, zp_prev, zp_next
swap_xy_3data calls comm_col, yp_prev, yp_next
swap_xy_3data_inv calls comm_col, yp_prev, yp_next