gasdev – ALaDyn
gasdev Subroutine
23 statements
Source File
public subroutine gasdev(dev)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(out) :: dev
Called by
Contents
None
Call graph
bunch_gen calls gasdev
one_layer_nano_tubes calls gasdev
add_particles calls gasdev
ionization_electrons_inject calls gasdev
pspecies_distribute calls gasdev
env_ionization_electrons_inject calls gasdev
ionization_cycle calls ionization_electrons_inject, env_ionization_electrons_inject
particles_inject calls add_particles
part_distribute calls one_layer_nano_tubes
lp_window_xshift calls particles_inject
comoving_coordinate calls particles_inject
init calls part_distribute
lp_run calls lp_window_xshift, comoving_coordinate
start calls init
env_run calls lp_window_xshift, comoving_coordinate
lp_cycle calls lp_run
env_cycle calls env_run
aladyn calls start, lp_cycle, env_cycle