init – ALaDyn
init Subroutine
14 statements
Source File
public subroutine init()
Arguments
None
Calls
Called by
Contents
None
Call graph
init calls cp_pulse, set_envelope, part_distribute, lp_pulse
cp_pulse calls init_cp_fields, lp_end, loc_xgrid, lp_in, lpx
set_envelope calls xf_loc, lp_delay, lp_end, loc_xgrid, xc_loc, lp_in, y0_cent, init_gprof_envelope_field, lpx, init_envelope_field, z0_cent
part_distribute calls one_layer_nano_tubes, one_layer_nano_wires, multi_layer_threesp_target, multi_layer_twosp_target, preplasma_multisp, multi_layer_gas_target
lp_pulse calls xf_loc, init_lp_inc0_fields, lp_delay, lp_end, loc_xgrid, xc_loc, lp_in, y0_cent, lpx, z0_cent
one_layer_nano_tubes calls loc_ypt, mpi_yz_part_distrib, gasdev, ypt, loc_xpt, init_random_seed, p_alloc, loc_zpt, xpt, spec, loc_wghyz, wghpt, zpt
init_cp_fields calls get_laser_fields_cp, loc_xg, loc_zgrid, get_plane_wave_cp, loc_yg, loc_ygrid, loc_zg
one_layer_nano_wires calls loc_ypt, mpi_yz_part_distrib, set_pgrid_ind, ypt, loc_xpt, p_alloc, loc_zpt, xpt, spec, loc_wghyz, loc_wghx, wghpt, zpt
init_lp_inc0_fields calls get_plane_wave_lp, loc_xg, loc_zgrid, loc_yg, get_laser_gprof_fields_lp, get_laser_fields_lp, loc_ygrid, get_2dlaser_gprof_fields_lp, get_2dlaser_fields_lp, loc_zg
multi_layer_threesp_target calls set_uniform_yz_distrib, loc_xpt, p_alloc, xpt, spec, loc_wghx, wghpt
multi_layer_twosp_target calls set_uniform_yz_distrib, loc_xpt, p_alloc, xpt, spec, loc_wghx, wghpt
preplasma_multisp calls set_uniform_yz_distrib, loc_xpt, p_alloc, xpt, spec, loc_wghx, wghpt
init_gprof_envelope_field calls loc_xg, loc_zgrid, loc_yg, loc_ygrid, loc_zg
init_envelope_field calls loc_xg, loc_zgrid, loc_yg, loc_ygrid, loc_zg
multi_layer_gas_target calls set_uniform_yz_distrib, loc_xpt, p_alloc, mpi_x_part_distrib, xpt, spec, loc_wghx, wghpt
set_uniform_yz_distrib calls loc_ypt, mpi_yz_part_distrib, set_pgrid_ind, ypt, loc_zpt, loc_wghyz, zpt
mpi_yz_part_distrib calls loc_ypt, ypt, loc_zpt, loc_wghyz, zpt
set_pgrid_ind calls ypt, zpt
mpi_x_part_distrib calls loc_xpt, xpt, loc_wghx, wghpt
start calls init
aladyn calls start