intvec_distribute – ALaDyn
intvec_distribute Subroutine
15 statements
Source File
public subroutine intvec_distribute(ns, nc, nproc)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: ns
integer, intent(inout) :: nc(:)
integer, intent(in) :: nproc
Calls
Called by
Contents
None
Call graph
intvec_distribute calls mpi_recv, mpi_send, mpi_bcast
dump_data calls intvec_distribute
part_pdata_out calls intvec_distribute
part_high_gamma_out calls intvec_distribute
part_ionz_out calls intvec_distribute
restart calls intvec_distribute
part_numbers calls intvec_distribute
part_bdata_out calls intvec_distribute
lp_window_xshift calls part_numbers
env_cycle calls part_numbers, data_out, timing, env_run
data_out calls part_pdata_out
start calls restart
timing calls part_numbers
aladyn calls part_numbers, env_cycle, start, lp_cycle
lp_run calls lp_window_xshift
lp_cycle calls data_out, timing, lp_run
env_run calls lp_window_xshift