isprime – ALaDyn
isprime Function
12 statements
Source File
private function isprime(num)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: num
Return Value logical
Called by
Contents
None
Call graph
from_ppc_to_npx_npy_npz calls isprime
consistency_check_number_of_particles_comp calls from_ppc_to_npx_npy_npz
consistency_check_number_of_particles calls from_ppc_to_npx_npy_npz
read_input_nml calls consistency_check_number_of_particles_comp
read_main_input calls read_input_nml
start calls read_main_input
aladyn calls start