Lp_cycle – ALaDyn
Lp_cycle Subroutine
15 statements
Source File
subroutine Lp_cycle()
LP_CYCLE: collects the Laser-plasma dynamics evolved as a standard PIC.
Arguments
None
Calls
Called by
Contents
None
Call graph
lp_cycle calls lp_run, timing, data_out, error_message
lp_run calls lp_window_xshift, comoving_coordinate, lpf2_evolve
timing calls tot_num_part, max_pmemory_check, part_numbers
data_out calls part_pdata_out, env_fields_out, fields_out_new, fields_out, env_two_fields_out, create_timestep_folder, envar, fluid_den_mom_out, prl_den_energy_interp, den_energy_out
lp_window_xshift calls part_numbers, fluid_left_xshift, fields_left_xshift, particles_inject, cell_part_dist
part_pdata_out calls mpi_write_part, loc_npart, intvec_distribute, endian
tot_num_part calls loc_npart
env_fields_out calls exchange_pdata
max_pmemory_check calls allreduce_dpreal
fields_out_new calls mpi_write_field, endian
fields_out calls endian, exchange_pdata
env_two_fields_out calls exchange_pdata
comoving_coordinate calls particles_inject, cell_part_dist
envar calls envelope_struct_data, loc_npart, mass, enb_bunch, allreduce_dpreal
part_numbers calls loc_npart, intvec_distribute
fluid_den_mom_out calls endian, exchange_pdata
lpf2_evolve calls set_momentum_density_flux, loc_npart, init_random_seed, update_adam_bash_fluid_variables, ion_min, ebfp, fluid_curr_accumulate, spec, jc, advance_lpf_fields, atomic_number, pfields_prepare
prl_den_energy_interp calls loc_npart, env, den_zyxbd, mass, loc_yg, spec, jc, loc_zg
den_energy_out calls endian, exchange_pdata
envelope_struct_data calls allreduce_dpreal
mpi_write_part calls mpi_file_close, mpi_file_set_view, mpi_file_write, mpi_file_open
update_adam_bash_fluid_variables calls lorentz_fact, field_xyzbd, unit_charge, fill_ebfield_yzxbdsdata, nc_fluid_density_momenta
fluid_left_xshift calls exchange_bdx_data
fields_left_xshift calls exchange_bdx_data
particles_inject calls loc_npart, add_particles, v_realloc
fluid_curr_accumulate calls field_xyzbd, unit_charge, fill_ebfield_yzxbdsdata
mpi_write_field calls mpi_file_close, mpi_file_set_view, mpi_file_write, mpi_file_open
enb_bunch calls loc_npart, allreduce_dpreal, bunch_corr
advance_lpf_fields calls rote, ef_bds, rotb, field_xadvect, fill_ebfield_yzxbdsdata, bf_bds
cell_part_dist calls loc_npart, ebfp, spec, v_realloc
intvec_distribute calls mpi_send, mpi_recv, mpi_bcast
allreduce_dpreal calls mpi_allreduce
pfields_prepare calls field_xyzbd, fill_ebfield_yzxbdsdata
bunch_corr calls allreduce_dpreal
rote calls loc_yg, loc_zg
add_particles calls gasdev, init_random_seed
ef_bds calls loc_yg, loc_zg, loc_zgrid, loc_xg
rotb calls loc_yg, loc_zg
field_xadvect calls trid_der1
fill_ebfield_yzxbdsdata calls exchange_bdx_data
nc_fluid_density_momenta calls loc_yg, loc_zg
bf_bds calls loc_yg, loc_zg, loc_xg
aladyn calls lp_cycle