lp_pulse – ALaDyn
lp_pulse Subroutine
54 statements
Source File
public subroutine lp_pulse(lp_mod, part_in)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: lp_mod
real(kind=dp), intent(out) :: part_in
Calls
Called by
Contents
None
Call graph
lp_pulse calls xf_loc, init_lp_inc0_fields, xc_loc, lp_delay, lp_end, lpx, loc_xgrid, lp_in, y0_cent, z0_cent
init_lp_inc0_fields calls get_laser_fields_lp, loc_yg, loc_ygrid, get_plane_wave_lp, loc_zgrid, get_2dlaser_gprof_fields_lp, get_2dlaser_fields_lp, loc_zg, loc_xg, get_laser_gprof_fields_lp
init calls lp_pulse
start calls init
aladyn calls start