lp_run – ALaDyn
lp_run Subroutine
21 statements
Source File
public subroutine lp_run(t_loc, iter_loc)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: t_loc
integer, intent(in) :: iter_loc
Calls
Called by
Contents
None
Call graph
lp_run calls lp_window_xshift, lpf2_evolve, comoving_coordinate
lp_window_xshift calls cell_part_dist, fluid_left_xshift, particles_inject, fields_left_xshift, part_numbers
lpf2_evolve calls update_adam_bash_fluid_variables, atomic_number, ion_min, pfields_prepare, ebfp, set_momentum_density_flux, loc_npart, fluid_curr_accumulate, spec, init_random_seed, jc, advance_lpf_fields
comoving_coordinate calls cell_part_dist, particles_inject
cell_part_dist calls ebfp, loc_npart, spec, v_realloc
update_adam_bash_fluid_variables calls field_xyzbd, unit_charge, fill_ebfield_yzxbdsdata, nc_fluid_density_momenta, lorentz_fact
pfields_prepare calls field_xyzbd, fill_ebfield_yzxbdsdata
fluid_left_xshift calls exchange_bdx_data
particles_inject calls loc_npart, add_particles, v_realloc
fluid_curr_accumulate calls field_xyzbd, unit_charge, fill_ebfield_yzxbdsdata
fields_left_xshift calls exchange_bdx_data
part_numbers calls loc_npart, intvec_distribute
advance_lpf_fields calls rotb, rote, field_xadvect, ef_bds, fill_ebfield_yzxbdsdata, bf_bds
rotb calls loc_yg, loc_zg
rote calls loc_yg, loc_zg
intvec_distribute calls mpi_send, mpi_bcast, mpi_recv
field_xadvect calls trid_der1
add_particles calls gasdev, init_random_seed
ef_bds calls loc_yg, loc_zgrid, loc_zg, loc_xg
fill_ebfield_yzxbdsdata calls exchange_bdx_data
bf_bds calls loc_yg, loc_zg, loc_xg
nc_fluid_density_momenta calls loc_yg, loc_zg
lp_cycle calls lp_run
aladyn calls lp_cycle