lpf2_evolve – ALaDyn
lpf2_evolve Subroutine
47 statements
Source File
public subroutine lpf2_evolve(iter_loc)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: iter_loc
Calls
Called by
Contents
None
Call graph
lpf2_evolve calls update_adam_bash_fluid_variables, atomic_number, ion_min, pfields_prepare, ebfp, set_momentum_density_flux, loc_npart, fluid_curr_accumulate, spec, init_random_seed, jc, advance_lpf_fields
update_adam_bash_fluid_variables calls field_xyzbd, unit_charge, fill_ebfield_yzxbdsdata, nc_fluid_density_momenta, lorentz_fact
pfields_prepare calls field_xyzbd, fill_ebfield_yzxbdsdata
fluid_curr_accumulate calls field_xyzbd, unit_charge, fill_ebfield_yzxbdsdata
advance_lpf_fields calls rotb, rote, field_xadvect, ef_bds, fill_ebfield_yzxbdsdata, bf_bds
rotb calls loc_yg, loc_zg
rote calls loc_yg, loc_zg
field_xadvect calls trid_der1
ef_bds calls loc_yg, loc_zgrid, loc_zg, loc_xg
fill_ebfield_yzxbdsdata calls exchange_bdx_data
bf_bds calls loc_yg, loc_zg, loc_xg
nc_fluid_density_momenta calls loc_yg, loc_zg
lp_run calls lpf2_evolve
lp_cycle calls lp_run
aladyn calls lp_cycle