map2dy_part_sind – ALaDyn
map2dy_part_sind Subroutine
28 statements
Source File
public subroutine map2dy_part_sind(np, ic1, pt)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: np
integer, intent(in) :: ic1
real(kind=dp), intent(inout) :: pt(:,:)
Calls
Called by
Contents
None
Call graph
map2dy_part_sind calls invert_stretched_grid, invert_uniform_grid
map3d_part_sind calls map2dy_part_sind
set_local_2d_positions calls map2dy_part_sind
set_env_density calls set_local_2d_positions, set_local_3d_positions
esirkepov_2d_curr calls set_local_2d_positions
set_ion_efield calls set_local_2d_positions, set_local_3d_positions
set_ion_env_field calls set_local_2d_positions, set_local_3d_positions
set_env_acc calls set_local_2d_positions, set_local_3d_positions
set_local_3d_positions calls map3d_part_sind
set_grid_charge calls set_local_2d_positions, set_local_3d_positions
set_grid_env_den_energy calls set_local_2d_positions, set_local_3d_positions
set_part2d_hcell_acc calls set_local_2d_positions
set_env_grad_interp calls set_local_2d_positions, set_local_3d_positions
set_grid_den_energy calls set_local_2d_positions, set_local_3d_positions
set_grid_charge_and_jx calls set_local_2d_positions, set_local_3d_positions
ncdef_2d_curr calls set_local_2d_positions
curr_accumulate calls esirkepov_2d_curr, ncdef_2d_curr, esirkepov_3d_curr, ncdef_3d_curr
set_lpf_acc calls set_part2d_hcell_acc, set_part3d_hcell_acc
esirkepov_3d_curr calls set_local_3d_positions
ncdef_3d_curr calls set_local_3d_positions
set_part3d_hcell_acc calls set_local_3d_positions