multi_layer_gas_target – ALaDyn
multi_layer_gas_target Subroutine
424 statements
Source File
private subroutine multi_layer_gas_target(layer_mod, nyh_in, xf0)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: layer_mod
integer, intent(in) :: nyh_in
real(kind=dp), intent(in) :: xf0
Calls
Called by
Contents
None
Call graph
multi_layer_gas_target calls set_uniform_yz_distrib, loc_wghx, mpi_x_part_distrib, wghpt, loc_xpt, xpt, p_alloc, spec
set_uniform_yz_distrib calls loc_zpt, ypt, loc_ypt, mpi_yz_part_distrib, zpt, loc_wghyz, set_pgrid_ind
mpi_x_part_distrib calls loc_wghx, wghpt, loc_xpt, xpt
mpi_yz_part_distrib calls loc_zpt, ypt, loc_ypt, zpt, loc_wghyz
set_pgrid_ind calls ypt, zpt
part_distribute calls multi_layer_gas_target
init calls part_distribute
start calls init
aladyn calls start