multi_layer_threesp_target – ALaDyn
multi_layer_threesp_target Subroutine
168 statements
Source File
private subroutine multi_layer_threesp_target(nyh_in, xf0)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: nyh_in
real(kind=dp), intent(in) :: xf0
Calls
Called by
Contents
None
Call graph
multi_layer_threesp_target calls set_uniform_yz_distrib, loc_wghx, wghpt, loc_xpt, xpt, p_alloc, spec
set_uniform_yz_distrib calls loc_zpt, ypt, loc_ypt, mpi_yz_part_distrib, zpt, loc_wghyz, set_pgrid_ind
mpi_yz_part_distrib calls loc_zpt, ypt, loc_ypt, zpt, loc_wghyz
set_pgrid_ind calls ypt, zpt
part_distribute calls multi_layer_threesp_target
init calls part_distribute
start calls init
aladyn calls start