one_layer_nano_tubes – ALaDyn
one_layer_nano_tubes Subroutine
257 statements
Source File
private subroutine one_layer_nano_tubes(nyh_in, xf0)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: nyh_in
real(kind=dp), intent(in) :: xf0
Calls
Called by
Contents
None
Call graph
one_layer_nano_tubes calls loc_zpt, gasdev, ypt, wghpt, loc_xpt, xpt, loc_ypt, init_random_seed, p_alloc, mpi_yz_part_distrib, spec, zpt, loc_wghyz
mpi_yz_part_distrib calls loc_zpt, ypt, loc_ypt, zpt, loc_wghyz
part_distribute calls one_layer_nano_tubes
init calls part_distribute
start calls init
aladyn calls start