one_layer_nano_wires – ALaDyn
one_layer_nano_wires Subroutine
375 statements
Source File
private subroutine one_layer_nano_wires(nyh_in, xf0)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: nyh_in
real(kind=dp), intent(in) :: xf0
Calls
Called by
Contents
None
Call graph
one_layer_nano_wires calls loc_zpt, loc_wghx, ypt, wghpt, loc_xpt, xpt, loc_ypt, p_alloc, mpi_yz_part_distrib, spec, zpt, loc_wghyz, set_pgrid_ind
mpi_yz_part_distrib calls loc_zpt, ypt, loc_ypt, zpt, loc_wghyz
set_pgrid_ind calls ypt, zpt
part_distribute calls one_layer_nano_wires
init calls part_distribute
start calls init
aladyn calls start