part_pdata_out – ALaDyn
part_pdata_out Subroutine
116 statements
Source File
public subroutine part_pdata_out(timenow, xmin_out, xmax_out, ymax_out, pid, jmp)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: timenow
real(kind=dp), intent(in) :: xmin_out
real(kind=dp), intent(in) :: xmax_out
real(kind=dp), intent(in) :: ymax_out
integer, intent(in) :: pid
integer, intent(in) :: jmp
Calls
Called by
Contents
None
Call graph
part_pdata_out calls intvec_distribute, mpi_write_part, loc_npart, endian
intvec_distribute calls mpi_send, mpi_bcast, mpi_recv
mpi_write_part calls mpi_file_write, mpi_file_open, mpi_file_set_view, mpi_file_close
data_out calls part_pdata_out
lp_cycle calls data_out
env_cycle calls data_out
aladyn calls lp_cycle, env_cycle