Part_numbers – ALaDyn
Part_numbers Subroutine
26 statements
Source File
public subroutine Part_numbers()
Arguments
None
Calls
Called by
Contents
None
Call graph
part_numbers calls intvec_distribute, loc_npart
intvec_distribute calls mpi_recv, mpi_send, mpi_bcast
lp_window_xshift calls part_numbers
timing calls part_numbers
env_cycle calls part_numbers, timing, env_run
aladyn calls part_numbers, env_cycle, lp_cycle
lp_run calls lp_window_xshift
lp_cycle calls timing, lp_run
env_run calls lp_window_xshift