part_distribute – ALaDyn
part_distribute Subroutine
38 statements
Source File
public subroutine part_distribute(id, xf0)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: id
real(kind=dp), intent(in) :: xf0
Calls
Called by
Contents
None
Call graph
part_distribute calls multi_layer_gas_target, one_layer_nano_tubes, multi_layer_threesp_target, preplasma_multisp, one_layer_nano_wires, multi_layer_twosp_target
multi_layer_gas_target calls set_uniform_yz_distrib, loc_wghx, mpi_x_part_distrib, wghpt, loc_xpt, xpt, p_alloc, spec
one_layer_nano_tubes calls loc_zpt, gasdev, wghpt, loc_xpt, ypt, xpt, loc_ypt, init_random_seed, p_alloc, spec, mpi_yz_part_distrib, zpt, loc_wghyz
multi_layer_threesp_target calls set_uniform_yz_distrib, loc_wghx, wghpt, loc_xpt, xpt, p_alloc, spec
preplasma_multisp calls set_uniform_yz_distrib, loc_wghx, wghpt, loc_xpt, xpt, p_alloc, spec
one_layer_nano_wires calls loc_zpt, loc_wghx, wghpt, loc_xpt, ypt, xpt, loc_ypt, p_alloc, spec, mpi_yz_part_distrib, zpt, loc_wghyz, set_pgrid_ind
multi_layer_twosp_target calls set_uniform_yz_distrib, loc_wghx, wghpt, loc_xpt, xpt, p_alloc, spec
set_uniform_yz_distrib calls loc_zpt, ypt, loc_ypt, mpi_yz_part_distrib, zpt, loc_wghyz, set_pgrid_ind
mpi_x_part_distrib calls loc_wghx, wghpt, loc_xpt, xpt
mpi_yz_part_distrib calls loc_zpt, ypt, loc_ypt, zpt, loc_wghyz
set_pgrid_ind calls ypt, zpt
init calls part_distribute
start calls init
aladyn calls start