part_bdata_out – ALaDyn
part_bdata_out Subroutine
90 statements
Source File
public subroutine part_bdata_out(timenow, pid, jmp)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: timenow
integer, intent(in) :: pid
integer, intent(in) :: jmp
Calls
Contents
None
Call graph
part_bdata_out calls intvec_distribute, mpi_write_part, loc_npart, endian
intvec_distribute calls mpi_send, mpi_bcast, mpi_recv
mpi_write_part calls mpi_file_write, mpi_file_open, mpi_file_set_view, mpi_file_close