preplasma_multisp – ALaDyn
preplasma_multisp Subroutine
189 statements
Source File
private subroutine preplasma_multisp(nyh_in, xf0)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: nyh_in
real(kind=dp), intent(in) :: xf0
Calls
Called by
Contents
None
Call graph
preplasma_multisp calls set_uniform_yz_distrib, loc_wghx, wghpt, loc_xpt, xpt, p_alloc, spec
set_uniform_yz_distrib calls loc_zpt, ypt, loc_ypt, mpi_yz_part_distrib, zpt, loc_wghyz, set_pgrid_ind
mpi_yz_part_distrib calls loc_zpt, ypt, loc_ypt, zpt, loc_wghyz
set_pgrid_ind calls ypt, zpt
part_distribute calls preplasma_multisp
init calls part_distribute
start calls init
aladyn calls start