restart – ALaDyn
restart Subroutine
369 statements
Source File
public subroutine restart(it_loc, tloc)
Arguments
Type Intent Optional Attributes Name
integer, intent(out) :: it_loc
real(kind=dp), intent(out) :: tloc
Calls
Called by
Contents
None
Call graph
restart calls loc_npart, loc_ypt, exchange_2d_grdata, env1, env, real_bcast, p_alloc, ebf, up, fluid_x_profile, loc_zpt, vint_bcast, xpt, spec, exchange_1d_grdata, up0, loc_wghyz, fluid_yz_profile, intvec_distribute, vint_2d_bcast, wghpt
real_bcast calls mpi_bcast
vint_bcast calls mpi_bcast
intvec_distribute calls mpi_recv, mpi_send, mpi_bcast
start calls restart
aladyn calls start