set_grid_den_energy – ALaDyn
set_grid_den_energy Subroutine
87 statements
Source File
public subroutine set_grid_den_energy(sp_loc, pt, eden, np)
Arguments
Type Intent Optional Attributes Name
type(species), intent(in) :: sp_loc
real(kind=dp), intent(inout) :: pt(:,:)
real(kind=dp), intent(inout) :: eden(:,:,:,:)
integer, intent(in) :: np
Calls
Contents
None
Call graph
set_grid_den_energy calls set_local_2d_positions, qden_3d_wgh, set_part_gamma, set_local_3d_positions, qden_1d_wgh, qden_2d_wgh
set_local_2d_positions calls map2dy_part_sind
set_local_3d_positions calls map3d_part_sind
map2dy_part_sind calls invert_stretched_grid, invert_uniform_grid
map3d_part_sind calls map2dy_part_sind, map2dz_part_sind
map2dz_part_sind calls invert_stretched_grid, invert_uniform_grid