set_wake_potential – ALaDyn
set_wake_potential Subroutine
21 statements
Source File
public subroutine set_wake_potential()
Arguments
None
Calls
Contents
None
Call graph
set_wake_potential calls loc_npart, fill_curr_yzxbdsdata, spec, fill_density_data, jc, fft_2d_psolv
fill_curr_yzxbdsdata calls exchange_bdx_data
fill_density_data calls z, loc_ygrid, y, x, loc_zgrid
fft_2d_psolv calls ftw_init, beam_2d_potential, pftw2d_sc, pftw2d, ftw_end, ft_overset_grid, all_gather_dpreal, mpi_yzft_ord, mpi_ftw_alloc, mpi_ftw_dalloc, unif_to_str_field_interp
pftw2d_sc calls ftw1d_sc, swap_xz_3data_inv, swap_xz_3data, swap_xy_3data, swap_xy_3data_inv
pftw2d calls swap_xz_3data_inv, swap_xz_3data, ftw1d, swap_xy_3data, swap_xy_3data_inv
ft_overset_grid calls comm_col, yp_prev, yp_next, zp_prev, zp_next
unif_to_str_field_interp calls zft_ind, loc_zft, loc_yft, loc_yg, yft_ind, loc_zg
ftw1d_sc calls fftw_execute_r2r, determine_kind, logical_dimension
swap_xz_3data_inv calls comm_col, zp_prev, zp_next
swap_xz_3data calls comm_col, zp_prev, zp_next
ftw1d calls fftw_execute_dft_c2r, fftw_execute_dft_r2c
swap_xy_3data calls comm_col, yp_prev, yp_next
swap_xy_3data_inv calls comm_col, yp_prev, yp_next