Start – ALaDyn
Start Subroutine
193 statements
Source File
public subroutine Start()
Start subroutine. It reads the input file, initializes the variables and allocates the needed arrays before to start the simulation.
Arguments
None
Calls
Called by
Contents
None
Call graph
start calls set_initial_param, init, mpi_buffer_alloc, loc_yftgrid, set_field_param, yft_ind, set_output_grid, create_initial_folders, write_read_nml, ion_min, start_parallel, set_fyzxgrid, float, mpi_barrier, set_ftgrid, loc_yg, v_alloc, restart, end_parallel, read_main_input, fluid_alloc, mpi_loc_grid, atomic_number, set_loc_grid_param, loc_yft, loc_ygrid, set_fxgrid
set_initial_param calls y, set_grid, z
init calls set_envelope, cp_pulse, part_distribute, lp_pulse
set_ftgrid calls select_str_to_ft_grid, set_ftyzgrid
restart calls loc_npart, loc_ypt, exchange_2d_grdata, env1, env, real_bcast, p_alloc, ebf, up, fluid_x_profile, loc_zpt, vint_bcast, xpt, spec, exchange_1d_grdata, up0, loc_wghyz, fluid_yz_profile, intvec_distribute, vint_2d_bcast, wghpt
read_main_input calls read_input_nml
read_input_nml calls consistency_check_grid, consistency_check_number_of_particles_comp
set_envelope calls xf_loc, lp_delay, lp_end, loc_xgrid, xc_loc, lp_in, y0_cent, init_gprof_envelope_field, lpx, init_envelope_field, z0_cent
cp_pulse calls init_cp_fields, lp_end, loc_xgrid, lp_in, lpx
part_distribute calls one_layer_nano_tubes, one_layer_nano_wires, multi_layer_threesp_target, multi_layer_gas_target, preplasma_multisp, multi_layer_twosp_target
real_bcast calls mpi_bcast
vint_bcast calls mpi_bcast
intvec_distribute calls mpi_send, mpi_recv, mpi_bcast
lp_pulse calls xf_loc, init_lp_inc0_fields, lp_delay, lp_end, loc_xgrid, xc_loc, lp_in, y0_cent, lpx, z0_cent
one_layer_nano_tubes calls loc_ypt, p_alloc, loc_zpt, xpt, spec, loc_wghyz, wghpt, mpi_yz_part_distrib, gasdev, ypt, loc_xpt, init_random_seed, zpt
init_cp_fields calls loc_yg, loc_ygrid, get_laser_fields_cp, loc_xg, loc_zgrid, get_plane_wave_cp, loc_zg
one_layer_nano_wires calls loc_ypt, p_alloc, loc_zpt, xpt, spec, loc_wghyz, wghpt, mpi_yz_part_distrib, set_pgrid_ind, ypt, loc_xpt, loc_wghx, zpt
init_lp_inc0_fields calls loc_yg, loc_ygrid, get_plane_wave_lp, loc_xg, loc_zgrid, get_laser_gprof_fields_lp, get_laser_fields_lp, get_2dlaser_gprof_fields_lp, get_2dlaser_fields_lp, loc_zg
multi_layer_threesp_target calls p_alloc, xpt, spec, wghpt, set_uniform_yz_distrib, loc_xpt, loc_wghx
multi_layer_gas_target calls p_alloc, xpt, spec, wghpt, set_uniform_yz_distrib, loc_xpt, mpi_x_part_distrib, loc_wghx
preplasma_multisp calls p_alloc, xpt, spec, wghpt, set_uniform_yz_distrib, loc_xpt, loc_wghx
init_gprof_envelope_field calls loc_yg, loc_ygrid, loc_xg, loc_zgrid, loc_zg
consistency_check_number_of_particles_comp calls from_ppc_to_npx_npy_npz
init_envelope_field calls loc_yg, loc_ygrid, loc_xg, loc_zgrid, loc_zg
multi_layer_twosp_target calls p_alloc, xpt, spec, wghpt, set_uniform_yz_distrib, loc_xpt, loc_wghx
set_uniform_yz_distrib calls loc_ypt, loc_zpt, loc_wghyz, mpi_yz_part_distrib, set_pgrid_ind, ypt, zpt
mpi_yz_part_distrib calls loc_ypt, loc_zpt, loc_wghyz, ypt, zpt
set_pgrid_ind calls ypt, zpt
from_ppc_to_npx_npy_npz calls isprime
mpi_x_part_distrib calls xpt, wghpt, loc_xpt, loc_wghx
aladyn calls start