timing – ALaDyn
timing Subroutine
29 statements
Source File
public subroutine timing()
Arguments
None
Calls
Called by
Contents
None
Call graph
timing calls max_pmemory_check, tot_num_part, part_numbers
max_pmemory_check calls allreduce_dpreal
tot_num_part calls loc_npart
part_numbers calls intvec_distribute, loc_npart
intvec_distribute calls mpi_recv, mpi_send, mpi_bcast
allreduce_dpreal calls mpi_allreduce
lp_cycle calls timing
env_cycle calls timing
aladyn calls lp_cycle, env_cycle