aladyn – ALaDyn
aladyn Program
168 statements
Source File
Uses
start_all
diag_part_and_fields
run_data_info
pic_out_util
pic_out
init_beam_part_distrib
pic_evolve
env_evolve
Calls
Contents
Subroutines
Lp_cycle Env_cycle data_out
Subroutines
subroutine Lp_cycle()
LP_CYCLE: collects the Laser-plasma dynamics evolved as a standard PIC.
Arguments
None
subroutine Env_cycle()
Arguments
None
subroutine data_out()
Arguments
None
Call graph
aladyn calls final_run_info, env_cycle, max_pmemory_check, lp_cycle, initial_run_info, start, end_parallel, part_numbers, mpi_barrier
env_cycle calls part_numbers, beam_inject, timing, error_message, data_out, env_run
max_pmemory_check calls allreduce_dpreal
lp_cycle calls lp_run, timing, error_message, data_out
start calls end_parallel, mpi_barrier, set_initial_param, init, mpi_buffer_alloc, loc_yftgrid, set_field_param, yft_ind, set_output_grid, create_initial_folders, write_read_nml, ion_min, start_parallel, set_fyzxgrid, float, set_ftgrid, loc_yg, v_alloc, restart, read_main_input, fluid_alloc, mpi_loc_grid, atomic_number, set_loc_grid_param, loc_yft, loc_ygrid, set_fxgrid
part_numbers calls loc_npart, intvec_distribute
lp_run calls comoving_coordinate, lpf2_evolve, lp_window_xshift
beam_inject calls loc_npart, pot, mpi_beam_ftgrid_distribute, beam_data, bunch, ebf_bunch, lp_end, init_random_seed, p_alloc, ebf, mpi_beam_distribute, ebfb, ebfp, spec, fill_ebfield_yzxbdsdata, jc, initial_beam_fields, loc_nbpart
set_initial_param calls y, set_grid, z
init calls set_envelope, cp_pulse, part_distribute, lp_pulse
timing calls max_pmemory_check, part_numbers, tot_num_part
data_out calls fluid_den_mom_out, env_fields_out, create_timestep_folder, prl_den_energy_interp, part_pdata_out, fields_out_new, envar, env_two_fields_out, fields_out, den_energy_out
set_ftgrid calls select_str_to_ft_grid, set_ftyzgrid
restart calls loc_npart, intvec_distribute, loc_ypt, exchange_2d_grdata, env1, env, p_alloc, real_bcast, ebf, up, fluid_x_profile, loc_zpt, vint_bcast, xpt, spec, exchange_1d_grdata, up0, loc_wghyz, fluid_yz_profile, vint_2d_bcast, wghpt
read_main_input calls read_input_nml
intvec_distribute calls mpi_send, mpi_recv, mpi_bcast
allreduce_dpreal calls mpi_allreduce
env_run calls comoving_coordinate, env_lpf2_evolve, lp_window_xshift
read_input_nml calls consistency_check_grid, consistency_check_number_of_particles_comp
set_envelope calls lp_end, xf_loc, lp_delay, loc_xgrid, xc_loc, lp_in, y0_cent, init_gprof_envelope_field, lpx, init_envelope_field, z0_cent
cp_pulse calls lp_end, init_cp_fields, loc_xgrid, lp_in, lpx
mpi_beam_ftgrid_distribute calls bunch, ebfb, loc_nbpart
fluid_den_mom_out calls endian, exchange_pdata
beam_data calls ebfb, exchange_2d_grdata, unit_charge
part_distribute calls one_layer_nano_tubes, one_layer_nano_wires, multi_layer_threesp_target, multi_layer_gas_target, preplasma_multisp, multi_layer_twosp_target
env_fields_out calls exchange_pdata
comoving_coordinate calls particles_inject, cell_part_dist
real_bcast calls mpi_bcast
prl_den_energy_interp calls loc_npart, loc_yg, env, spec, jc, loc_zg, den_zyxbd, mass
lpf2_evolve calls loc_npart, ion_min, atomic_number, ebfp, spec, jc, set_momentum_density_flux, init_random_seed, update_adam_bash_fluid_variables, fluid_curr_accumulate, advance_lpf_fields, pfields_prepare
mpi_beam_distribute calls bunch, ebfb, loc_nbpart
env_lpf2_evolve calls loc_npart, ion_min, atomic_number, init_random_seed, ebfp, spec, jc, env_amp_two_fields_prepare, env_two_fields_average, update_adam_bash_fluid_variables, enable_ionization, curr_mpi_collect, set_env_density, fluid_curr_accumulate, advance_lpf_fields, env_amp_prepare, env_fields_average, env_den_collect, set_env_momentum_density_flux, flux, advance_lpf_envelope
part_pdata_out calls loc_npart, intvec_distribute, mpi_write_part, endian
fields_out_new calls mpi_write_field, endian
vint_bcast calls mpi_bcast
envar calls loc_npart, allreduce_dpreal, envelope_struct_data, enb_bunch, mass
fill_ebfield_yzxbdsdata calls exchange_bdx_data
env_two_fields_out calls exchange_pdata
lp_window_xshift calls part_numbers, fluid_left_xshift, fields_left_xshift, particles_inject, cell_part_dist
tot_num_part calls loc_npart
fields_out calls endian, exchange_pdata
initial_beam_fields calls loc_yg, loc_zg
lp_pulse calls lp_end, xf_loc, init_lp_inc0_fields, lp_delay, loc_xgrid, xc_loc, lp_in, y0_cent, lpx, z0_cent
den_energy_out calls endian, exchange_pdata
one_layer_nano_tubes calls loc_ypt, init_random_seed, p_alloc, loc_zpt, xpt, spec, loc_wghyz, wghpt, mpi_yz_part_distrib, gasdev, ypt, loc_xpt, zpt
envelope_struct_data calls allreduce_dpreal
mpi_write_part calls mpi_file_close, mpi_file_set_view, mpi_file_write, mpi_file_open
env_amp_two_fields_prepare calls env_grad
init_cp_fields calls loc_yg, loc_ygrid, loc_zg, get_laser_fields_cp, loc_xg, loc_zgrid, get_plane_wave_cp
one_layer_nano_wires calls loc_ypt, p_alloc, loc_zpt, xpt, spec, loc_wghyz, wghpt, mpi_yz_part_distrib, set_pgrid_ind, ypt, loc_xpt, loc_wghx, zpt
update_adam_bash_fluid_variables calls fill_ebfield_yzxbdsdata, unit_charge, lorentz_fact, field_xyzbd, nc_fluid_density_momenta
fluid_left_xshift calls exchange_bdx_data
init_lp_inc0_fields calls loc_yg, loc_ygrid, loc_zg, get_plane_wave_lp, loc_xg, loc_zgrid, get_laser_gprof_fields_lp, get_laser_fields_lp, get_2dlaser_gprof_fields_lp, get_2dlaser_fields_lp
fields_left_xshift calls exchange_bdx_data
enb_bunch calls loc_npart, allreduce_dpreal, bunch_corr
curr_mpi_collect calls fill_curr_yzxbdsdata, djc, jc_xyzbd
multi_layer_threesp_target calls p_alloc, xpt, spec, wghpt, set_uniform_yz_distrib, loc_xpt, loc_wghx
particles_inject calls loc_npart, add_particles, v_realloc
fluid_curr_accumulate calls fill_ebfield_yzxbdsdata, unit_charge, field_xyzbd
mpi_write_field calls mpi_file_close, mpi_file_set_view, mpi_file_write, mpi_file_open
advance_lpf_fields calls fill_ebfield_yzxbdsdata, rote, ef_bds, rotb, field_xadvect, bf_bds
multi_layer_gas_target calls p_alloc, xpt, spec, wghpt, set_uniform_yz_distrib, loc_xpt, mpi_x_part_distrib, loc_wghx
env_amp_prepare calls env_grad
env_fields_average calls env_grad
env_den_collect calls loc_yg, loc_zg, fill_curr_yzxbdsdata, den_zyxbd
cell_part_dist calls loc_npart, ebfp, spec, v_realloc
advance_lpf_envelope calls fill_ebfield_yzxbdsdata, env_lpf_solve, env_maxw_solve, env_bds
pfields_prepare calls fill_ebfield_yzxbdsdata, field_xyzbd
preplasma_multisp calls p_alloc, xpt, spec, wghpt, set_uniform_yz_distrib, loc_xpt, loc_wghx
init_gprof_envelope_field calls loc_yg, loc_ygrid, loc_zg, loc_xg, loc_zgrid
consistency_check_number_of_particles_comp calls from_ppc_to_npx_npy_npz
init_envelope_field calls loc_yg, loc_ygrid, loc_zg, loc_xg, loc_zgrid
multi_layer_twosp_target calls p_alloc, xpt, spec, wghpt, set_uniform_yz_distrib, loc_xpt, loc_wghx
set_uniform_yz_distrib calls loc_ypt, loc_zpt, loc_wghyz, mpi_yz_part_distrib, set_pgrid_ind, ypt, zpt
env_lpf_solve calls pp_lapl
fill_curr_yzxbdsdata calls exchange_bdx_data
mpi_yz_part_distrib calls loc_ypt, loc_zpt, loc_wghyz, ypt, zpt
bunch_corr calls allreduce_dpreal
set_pgrid_ind calls ypt, zpt
rote calls loc_yg, loc_zg
env_maxw_solve calls potential_lapl
add_particles calls init_random_seed, gasdev
env_bds calls loc_yg, loc_zg
ef_bds calls loc_yg, loc_zg, loc_xg, loc_zgrid
from_ppc_to_npx_npy_npz calls isprime
rotb calls loc_yg, loc_zg
field_xadvect calls trid_der1
mpi_x_part_distrib calls xpt, wghpt, loc_xpt, loc_wghx
nc_fluid_density_momenta calls loc_yg, loc_zg
bf_bds calls loc_yg, loc_zg, loc_xg
pp_lapl calls loc_yg, loc_zg